# This is the Ansible playbook that provisions the instances created by
# Drifter.  For more information Ansible playbooks, see the Ansible 
# project documentation at http://ansible.cc/docs/.

- include: playbooks/facts.yml
- include: playbooks/common.yml
- include: playbooks/frontend.yml
- include: playbooks/register.yml

