# Install common packages on all systems in 
# the cluster.
- hosts: all
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:

  # Install packages using apt.
  - action: apt pkg=$item
    with_items:
    - puppet
    - git-core
    - ruby-json
    - apache2
